# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuariosServiceStub:
    """Servicio: operaciones disponibles.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUsuario = channel.unary_unary(
                '/usuarios.UsuariosService/CrearUsuario',
                request_serializer=usuarios__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/usuarios.UsuariosService/ListarUsuarios',
                request_serializer=usuarios__pb2.ListarRequest.SerializeToString,
                response_deserializer=usuarios__pb2.ListarResponse.FromString,
                _registered_method=True)
        self.SuscribirUsuarios = channel.unary_stream(
                '/usuarios.UsuariosService/SuscribirUsuarios',
                request_serializer=usuarios__pb2.SuscripcionRequest.SerializeToString,
                response_deserializer=usuarios__pb2.UsuarioResponse.FromString,
                _registered_method=True)


class UsuariosServiceServicer:
    """Servicio: operaciones disponibles.
    """

    def CrearUsuario(self, request, context):
        """Crea un usuario.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Lista todos los usuarios registrados.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuscribirUsuarios(self, request, context):
        """Suscripción: el servidor envía usuarios en flujo (streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuariosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUsuario,
                    request_deserializer=usuarios__pb2.UsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.UsuarioResponse.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=usuarios__pb2.ListarRequest.FromString,
                    response_serializer=usuarios__pb2.ListarResponse.SerializeToString,
            ),
            'SuscribirUsuarios': grpc.unary_stream_rpc_method_handler(
                    servicer.SuscribirUsuarios,
                    request_deserializer=usuarios__pb2.SuscripcionRequest.FromString,
                    response_serializer=usuarios__pb2.UsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuarios.UsuariosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuarios.UsuariosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuariosService:
    """Servicio: operaciones disponibles.
    """

    @staticmethod
    def CrearUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuariosService/CrearUsuario',
            usuarios__pb2.UsuarioRequest.SerializeToString,
            usuarios__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuariosService/ListarUsuarios',
            usuarios__pb2.ListarRequest.SerializeToString,
            usuarios__pb2.ListarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuscribirUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/usuarios.UsuariosService/SuscribirUsuarios',
            usuarios__pb2.SuscripcionRequest.SerializeToString,
            usuarios__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
